### PR TITLE
add redis reconcile

### PR DESCRIPTION
**Pull request by Ghostbaby**
Signed-off-by: zhuhuijun zhuhuijunzhj@gmail.com

### CODE REVIEW

**Comment by Ghostbaby** [comment]
type Cache interface {
	Reconcile() *reconciler.Results
	Deploy() error
	Readiness() error
	DownScale() error
	RollingUpgrades()
}

**Comment by bitsf** [comment]
this pr https://github.com/goharbor/harbor/pull/11155 is adding sentinel to harbor

**Pull request closed without merging**
